version: "3.8"
services:
  database:
    ports:
      - 5432:5432
    build:
      context: ./Docker
      dockerfile: database.Dockerfile
    environment:
      - POSTGRES_USER=samrat
      - POSTGRES_PASSWORD=Samrat@1234
      - POSTGRES_DB=inbound

    volumes:
      - ./db:/var/lib/postgresql/data/
    networks:
      - network2

  redis:
    ports:
      - 6379:6379
    image: redis
    restart: always
    volumes:
      - cache:/data
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - network2

  backend:
    build: ./inbound-backend
    command: bash -c "supervisord -c /supervisord.conf"
    ports:
      - 8000:8000
    depends_on:
      - database
      - redis
    volumes:
      - ./inbound-backend/:/app/
        # Mount 'supervisor.d' as its namesake in the root of the container
      - type: volume
        source: supervisor.d
        target: /supervisor.d
        read_only: false

      # Mount 'web_server_logs' as its namesake in the root of the container
      - type: volume
        source: web_server_logs
        target: /web_server_logs
        read_only: false

      # Mount '.history' as its namesake in the root of the container
      - type: volume
        source: .history
        target: /.history
        read_only: false
    restart: on-failure:2
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - network2

  frontend:
    build: ./inbound-frontend
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - database
      - backend
      - redis
    volumes:
      - ./inbound-frontend/:/app/
    networks:
      - network2

volumes:
  db:
  cache:
  web_server_logs:

  # This volume is for static files of backend
  static_backend:

  # This volume contains the supervisor.d conf files
  supervisor.d:

  # This volume contains the history files
  .history:

networks:
  network2:
